const TermsAndConditions = {
  title: "Terms and Conditions",
  lastUpdated: "Last Updated: 20 June 2025",
  sections: [
    {
      title: "1. About ZaveIt",
      content:
        "ZaveIt allows users to share posts that include a title, URL, thumbnail (if available), and author (if available). The app uses AI to generate up to 3 tags based on the title. Posts can be filtered by title or tags.",
    },
    {
      title: "2. Account and Authentication",
      content:
        "Users can sign in using their Google account through Firebase Authentication. You are responsible for maintaining the confidentiality of your credentials and for all activity that occurs under your account.",
    },
    {
      title: "3. Information We Collect",
      sections: [
        {
          content:
            "Your Google account ID, display name, and email address when signing in using Firebase Authentication.",
        },
        {
          content:
            "Post details shared by you, including title, URL, thumbnail (if available), and author (if provided).",
        },
        {
          content:
            "Tags generated by an AI model based on the post title.",
        },
      ],
    },
    {
      title: "4. Use of AI",
      content:
        "ZaveIt uses a large language model (LLM) to generate relevant tags for your posts based on their titles. While the tags are intended to be helpful, we do not guarantee their accuracy or relevance.",
    },
    {
      title: "5. User Content",
      content:
        "You are solely responsible for the content you share on ZaveIt. You agree not to post any illegal, harmful, offensive, or copyrighted content. We reserve the right to remove any content that violates these Terms.",
    },
    {
      title: "6. Data Storage and Security",
      content:
        "All data is stored in Firebase Firestore and linked to your authenticated Google account. We use industry-standard practices to protect your data.",
    },
    {
      title: "7. Account Deletion and Data Removal",
      content:
        "You may delete your account and all associated data at any time from within the app. This includes your account information, shared posts, and generated tags.",
    },
    {
      title: "8. Prohibited Use",
      content:
        "You agree not to misuse ZaveIt, including but not limited to unauthorized access, data scraping, or using automated tools to interact with the app.",
    },
    {
      title: "9. Intellectual Property",
      content:
        "All content generated by ZaveIt (such as tags) remains the property of the app. Your submitted content remains yours, but you grant us permission to store and process it as part of the app’s functionality.",
    },
    {
      title: "10. Changes to Terms",
      content:
        "We may update these Terms from time to time. We will notify users of any significant changes. Continued use of ZaveIt after updates constitutes acceptance of the new Terms.",
    },
    {
      title: "11. Disclaimer and Limitation of Liability",
      content:
        "ZaveIt is provided 'as is' without warranties of any kind. We are not responsible for any losses or damages resulting from the use of the app or third-party services.",
    },
    {
      title: "12. Contact",
      content:
        "For any questions about these Terms and Conditions, please contact us at hello@nativ.codes",
    },
  ],
};

const PrivacyPolicy = {
  title: "Privacy Policy",
  lastUpdated: "Last Updated: 20 June 2025",
  sections: [
    {
      title: "1. Introduction",
      content:
        "This Privacy Policy describes how ZaveIt collects, uses, and protects your information when you use the app. By using ZaveIt, you agree to the practices described in this policy.",
    },
    {
      title: "2. Information We Collect",
      sections: [
        {
          content:
            "Google Account Information: When you sign in using Google, we collect your Google ID, display name, and email address via Firebase Authentication.",
        },
        {
          content:
            "Post Content: When you share a post, we collect the title, URL, thumbnail (if available), and author (if provided).",
        },
        {
          content:
            "AI-Generated Tags: We use a large language model to generate up to 3 tags based on the post title.",
        },
        {
          content:
            "App Usage Data: We may collect anonymized data related to how you interact with ZaveIt to help improve app functionality and user experience.",
        },
      ],
    },
    {
      title: "3. How We Use Your Information",
      sections: [
        {
          content:
            "To authenticate users and manage accounts through Firebase Authentication.",
        },
        {
          content:
            "To store, display, and organize user-submitted posts and generated tags.",
        },
        {
          content:
            "To improve and personalize the user experience and functionality of the app.",
        },
        {
          content: "To comply with legal requirements, if necessary.",
        },
      ],
    },
    {
      title: "4. Data Storage and Security",
      content:
        "We store your data securely using Firebase Firestore and Authentication. Reasonable technical and organizational safeguards are in place to protect your information from unauthorized access, loss, or misuse.",
    },
    {
      title: "5. Sharing of Information",
      content:
        "We do not sell, rent, or share your personal data with third parties, except for trusted services that help operate the app (e.g., Firebase and AI providers), or when required by law.",
    },
    {
      title: "6. Your Rights",
      sections: [
        {
          content:
            "Access: You can request to access the personal data we hold about you.",
        },
        {
          content:
            "Correction: You may request corrections to inaccurate or incomplete data.",
        },
        {
          content:
            "Deletion: You can delete your account and all associated data directly from the app.",
        },
        {
          content:
            "Objection: You can object to certain types of data processing, where applicable.",
        },
      ],
    },
    {
      title: "7. Account and Data Deletion",
      content:
        "You can permanently delete your account and all associated data at any time from within the app. Once deleted, the data cannot be recovered.",
    },
    {
      title: "8. Changes to This Policy",
      content:
        "We may update this Privacy Policy from time to time. Significant changes will be communicated through the app. Continued use of ZaveIt after updates means you accept the updated policy.",
    },
    {
      title: "9. Contact",
      content:
        "If you have questions or concerns about this Privacy Policy, please contact us at hello@nativ.codes",
    },
  ],
};

export const Legal = {
  TermsAndConditions,
  PrivacyPolicy,
};
